### Register user (with phone)
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "testuser1@mathvn.vn",
  "password": "password123",
  "full_name": "Test User 1",
  "phone_number": "0933333333"
}

### Register user (without phone)
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "testuser2@mathvn.vn",
  "password": "password123",
  "full_name": "Test User 2",
  "phone_number": "0384215g155"
}

### Login with email
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email_or_phone": "admin@mathvn.vn",
  "password": "password123"
}

### Login with phone
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email_or_phone": "admin@mathvn.vn",
  "password": "password123"
}
